import string
import random

_jenis = [
    "Kehancuran",
    "Displin",
    "Pertumbuhan",
    "Transformasi",
    ]


_waktu = [
    "Beberapa tahun",
    "Sepuluh tahun",
    "Satu dekade",
    "Satu generasi",
    "Dua generasi",
    "Satu abad",
    "Satu millenium",
]

_lahan = [
    "Pertanian",
    "Otak",
    "Masa Kecil",
    "Masa Muda",
    "Kependudukan",
    "Kelas",
    "Cuaca",
    "Kloning",
    "Komunikasi",
    "Majelis",
    "Pengadilan",
    "Penyakit",
    "Drone",
    "Ekonomi",
    "Edukasi",
    "Hiburan",
    "Lingkungan",
    "Kesetaraan",
    "Keluarga",
    "Fashion",
    "Penerbangan",
    "Perhutanan",
    "Genetika",
    "Kelamin",
    "Pemerintahan",
    "jenis kelamin",
    "Kesehatan",
    "Hobby",
    "Rumah",
    "Identitas",
    "Serangga",
    "Hak Intelektual",
    "Jurnalisme",
    "Keadilan",
    "Pembelajaran",
    "Memori",
    "Pertambangan",
    "Bulan",
    "Musik",
    "Laut",
    "Minyak",
    "Jaman dulu",
    "Hewan piaraan",
    "Kekuatan",
    "Agama",
    "Robot",
    "Sex",
    "Belanja",
    "Ruang",
    "Olah Raga",
    "Teater",
    "Perjalanan",
    "Perang",
    "Air",
    "Kesehatan",
    "Perempuan",
    "Pekerjaan",
    "Zombi",
    "Kebun binatang",
    "Bebas",
]



_benda = [
    "Iklan",
    "Karya seni",
    "Minuman",
    "Buku",
    "Botol",
    "Kotak",
    "Brosur",
    "Bangunan",
    "Permen",
    "Pakaian",
    "Korporasi",
    "Alat",
    "Dokumen",
    "Acara",
    "Festival",
    "Bendera",
    "Permainan",
    "Hadiah",
    "Judul Utama",
    "Cangkokan",
    "Alat",
    "Alat musik",
    "Perhiasan",
    "Kit",
    "Hukum",
    "Logo",
    "Lotion",
    "Mesin",
    "Halaman depan Majalah",
    "Peta",
    "Topeng",
    "Monumen",
    "Passport",
    "Pil",
    "Tanaman",
    "Postcard",
    "Poster",
    "Produk",
    "Prostetik",
    "Pelayanan Publik",
    "Peninggalan Sejarah",
    "Ritual",
    "Pertunjukan",
    "Slogan",
    "Cemilan",
    "Lagu",
    "Souvenir",
    "Patung",
    "Stiker",
    "Simbol",
    "Kaos",
    "Tatoo",
    "Alat",
    "Mainan",
    "Kendaraan",
    "Video",
    "Senjata",
    "Bebas",
]


_mood = [
    "Kekaguman",
    "Pengasingan",
    "Hiburan",
    "Marah",
    "Kecemasan",
    "Kejanggalan",
    "Tenang",
    "Pesona",
    "Bersorak",
    "Kepuasan",
    "Rasa Ingin Tahu",
    "Dekadensi",
    "Sukacita",
    "Harga Diri",
    "Menjijikan",
    "Ketakutan",
    "Rasa Malu",
    "Kegembiraan",
    "Fascination",
    "Pesona",
    "Kekaguman",
    "Semangat",
    "Frustasi",
    "Syukur",
    "Kebahagiaan",
    "Kesenangan",
    "Harapan",
    "Kerinduan",
    "Pingsan",
    "Melankoli",
    "Sandiwara Sensasi",
    "Nostalgia",
    "Optimisme",
    "Kebiadaban",
    "Gairah",
    "Kenikmatan",
    "Kebanggan",
    "Rasionalitas",
    "Lega",
    "Kebencian",
    "Menghormati",
    "Kesedihan",
    "Kepuasan",
    "Ketenangan",
    "Malu",
    "Terkejut",
    "Duka",
    "Kejutan",
    "Kegelisahan",
    "Kehangatan",
    "Keanehan",
    "Kesejahteraan",
    "Takjub",
    "Khawatir",
    "Zen",
]

def inspirasi():
    benda = _benda[random.randint(0, len(_benda)-1)]
    mood = _mood[random.randint(0, len(_mood)-1)]
    lahan = _lahan[random.randint(0,len(_lahan)-1)]
    jenis = _jenis[random.randint(0,len(_jenis)-1)]
    waktu = _waktu[random.randint(0,len(_waktu)-1)]

    _inspirasi = f"Pada fase {jenis} rentang waktu {waktu}, dengan suasana {mood}, akan ada {benda} yang berkaitan dengan {lahan}. Apakah itu?"
    return _inspirasi

if __name__ == '__main__':
    print(inspirasi())
