# Generated by Django 3.1.2 on 2020-11-28 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=20, null=True)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('Teknologi', 'Teknologi'), ('Bisnis', 'Bisnis'), ('Pengembangan Diri', 'Pengembangan Diri'), ('Batch Khusus', 'Batch Khusus'), ('Koding Playlist', 'Koding Playlist'), ('Projects', 'Projects')], max_length=100)),
                ('summary', models.TextField()),
                ('tags', models.ManyToManyField(to='edukasi.Tag')),
            ],
        ),
    ]
