# Generated by Django 3.1.2 on 2020-11-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(max_length=10)),
                ('judul', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Label', 'Label'), ('Link Video', 'Link Video'), ('Konten Umum', 'Konten Umum'), ('Tugas', 'Tugas'), ('Quiz', 'Quiz'), ('Feedback', 'Feedback'), ('Url luar', 'Url luar'), ('File', 'File')], max_length=20)),
                ('link', models.CharField(max_length=250, null=True)),
                ('isi_tambahan', models.TextField(null=True)),
                ('materi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edukasi.materi')),
            ],
        ),
    ]
