# Generated by Django 3.1.2 on 2020-11-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0004_pengumuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='judul',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
