# Generated by Django 3.1.2 on 2020-12-08 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edukasi', '0007_auto_20201206_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=25)),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('deskripsi', models.TextField()),
                ('nilai_max', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField()),
                ('tipe', models.CharField(choices=[('Pilihan Ganda', 'Pilihan Ganda'), ('Betul / Salah', 'Betul / Salah'), ('Mencocokkan', 'Mencocokkan'), ('Jawab singkat', 'Jawab singkat'), ('Numerik', 'Numerik'), ('Essay', 'Essay'), ('Kumpul URL', 'Kumpul URL'), ('Lain-lain', 'Lain-lain')], max_length=20)),
                ('judul', models.CharField(max_length=25)),
                ('pertanyaan', models.TextField()),
                ('penjelasan', models.TextField()),
                ('benarsalah', models.BooleanField(blank=True, null=True)),
                ('multianswer', models.BooleanField(blank=True, default=False, null=True)),
                ('tags', models.ManyToManyField(to='edukasi.TagSoal')),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edukasi.ujian')),
            ],
        ),
        migrations.CreateModel(
            name='Komplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edukasi.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
