# Generated by Django 3.1.2 on 2020-12-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0011_auto_20201210_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='jawaban_essay',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='soal',
            name='jawaban_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
