# Generated by Django 3.1.2 on 2020-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0012_auto_20201210_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='tags',
            field=models.ManyToManyField(to='edukasi.TagSoal'),
        ),
    ]
