# Generated by Django 3.1.2 on 2020-12-12 06:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0014_auto_20201212_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='summary',
        ),
        migrations.AddField(
            model_name='materi',
            name='copywrite',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='materi',
            name='pendek',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='materi',
            name='rating',
            field=models.CharField(default='dasar', max_length=20),
        ),
        migrations.AlterField(
            model_name='materi',
            name='tentang_pengajar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
