# Generated by Django 3.1.2 on 2020-12-12 06:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0015_auto_20201212_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materi',
            name='frontpage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materi',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materi',
            name='playlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materi',
            name='rating',
            field=models.CharField(choices=[('dasar', 'dasar'), ('menengah', 'menengah'), ('mahir', 'mahir')], default='dasar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='isi',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='soal',
            name='jawaban_essay',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
