# Generated by Django 3.1.2 on 2020-12-17 01:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0016_auto_20201212_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ujian',
            new_name='Tugas',
        ),
        migrations.RenameField(
            model_name='soal',
            old_name='ujian',
            new_name='tugas',
        ),
        migrations.AlterField(
            model_name='soal',
            name='jawaban_essay',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soal',
            name='jawaban_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soal',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='edukasi.TagSoal'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='isi_tambahan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
