# Generated by Django 3.1.2 on 2020-12-17 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edukasi', '0017_auto_20201217_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edukasi.soal')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edukasi.topic')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edukasi.tugas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
