# Generated by Django 3.1.2 on 2020-12-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0020_jawaban_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='edukasi.TagSoal'),
        ),
    ]
