# Generated by Django 3.1.2 on 2020-12-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0021_auto_20201218_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jawaban',
            name='date_created',
        ),
    ]
