# Generated by Django 3.1.2 on 2020-12-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0022_remove_jawaban_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
