# Generated by Django 3.1.2 on 2021-01-04 13:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0023_auto_20201218_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='copywrite',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='kategori',
            field=models.CharField(choices=[('Teknologi', 'Teknologi'), ('Bisnis', 'Bisnis'), ('Pengembangan Diri', 'Pengembangan Diri'), ('Batch Khusus', 'Batch Khusus'), ('Koding Playlist', 'Koding Playlist'), ('Projects', 'Projects')], default='Teknologi', max_length=100),
        ),
        migrations.AlterField(
            model_name='materi',
            name='pengajar',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='edukasi.Tag'),
        ),
        migrations.AlterField(
            model_name='materi',
            name='tentang_pengajar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
