# Generated by Django 3.1.2 on 2021-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0031_auto_20210704_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='url_donasi',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
