# Generated by Django 3.1.2 on 2021-07-04 13:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0032_auto_20210704_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='tentang_pengajar',
        ),
        migrations.RemoveField(
            model_name='pengajar',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='pengajar',
            name='tentang_pengajar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='pengajar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edukasi.pengajar'),
        ),
    ]
