# Generated by Django 3.1.2 on 2021-07-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0033_auto_20210704_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='pengajar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edukasi.pengajar'),
            preserve_default=False,
        ),
    ]
