# Generated by Django 3.1.2 on 2021-07-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0032_auto_20210705_0617'),
        ('edukasi', '0034_auto_20210704_2034'),
    ]

    operations = [
    ]
