# Generated by Django 3.1.2 on 2021-07-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0035_merge_20210705_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='pengajar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edukasi.pengajar'),
        ),
        migrations.AlterField(
            model_name='pengajar',
            name='bank',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pengajar',
            name='lokasi',
            field=models.CharField(blank=True, default='Lokasi', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengajar',
            name='no_akun',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
