# Generated by Django 3.1.2 on 2021-07-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0036_auto_20210705_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='tanggal_mulai',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='tanggal_selesai',
        ),
    ]
