# Generated by Django 3.1.2 on 2021-07-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0037_auto_20210718_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='tanggal_mulai',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='tanggal_selesai',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
