# Generated by Django 3.1.2 on 2021-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0038_auto_20210718_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal_mulai',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal_selesai',
            field=models.DateTimeField(null=True),
        ),
    ]
