# Generated by Django 3.1.2 on 2021-08-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0040_auto_20210727_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='ytb_playlist_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
