# Generated by Django 3.1.2 on 2021-09-09 04:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0042_message_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 9, 4, 26, 31, 569994, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
