# Generated by Django 3.1.2 on 2021-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0043_auto_20210909_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rekening', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
