# Generated by Django 3.1.2 on 2021-11-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0044_akunbank_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
