# Generated by Django 3.1.2 on 2021-11-29 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0045_materi_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='kupon_account',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userext',
            name='last_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='userext',
            name='last_balance_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
